hl.on("hyprland.start", function()
  hl.exec_cmd("udiskie")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("swaync")
  hl.exec_cmd("pypr")
  hl.exec_cmd("kdeconnectd")
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("chromium --new-window --app=https://home.cuasar.cc")

  hl.exec_cmd([[bash -c '{ echo "=== Start $(date) ==="; ~/.scripts/focus-guard.sh; } >> /tmp/focus-guard.log 2>&1']])
  hl.exec_cmd([[bash -c '{ echo "=== Start $(date) ==="; ~/.scripts/brightness.sh daemon; } >> /tmp/brightness.log 2>&1']])
  hl.exec_cmd([[bash -c '{ echo "=== Start $(date) ==="; ~/.scripts/autoreload.sh --watch; } >> /tmp/autoreload.log 2>&1']])
  hl.exec_cmd([[bash -c '{ echo "=== Start $(date) ==="; ~/minishell/run.sh; } >> /tmp/minishell.log 2>&1']])

  hl.exec_cmd(string.format("hyprctl dispatch workspace %s", InitialWorkspace))
end)
