exec-once = udiskie &
exec-once = hypridle &
exec-once = swaync &
exec-once = pypr &
exec-once = kdeconnectd &
exec-once = hyprpm reload &
exec-once = awww-daemon &
exec-once = chromium --new-window --app=https://home.cuasar.cc &
exec-once = bash -c '{ echo "=== Start $(date) ==="; ~/.scripts/focus-guard.sh; } >> /tmp/focus-guard.log 2>&1' &
exec-once = bash -c '{ echo "=== Start $(date) ==="; ~/.scripts/brightness.sh daemon; } >> /tmp/brightness.log 2>&1' &
exec-once = bash -c '{ echo "=== Start $(date) ==="; ~/.scripts/autoreload.sh --watch; } >> /tmp/autoreload.log 2>&1' &
exec-once = bash -c '{ echo "=== Start $(date) ==="; ~/minishell/run.sh; } >> /tmp/minishell.log 2>&1' &
exec-once = hyprctl dispatch workspace $inital_workspace &
